//==================================================
//     Outputs that match the input variables
//==================================================
output "functions_path" {
  description = "The value of the `functions_path` input variable, or the default value if the input was `null`."
  value       = var.functions_path
}
output "unit_resolvers_path" {
  description = "The value of the `unit_resolvers_path` input variable, or the default value if the input was `null`."
  value       = var.unit_resolvers_path
}
output "pipeline_resolvers_path" {
  description = "The value of the `pipeline_resolvers_path` input variable, or the default value if the input was `null`."
  value       = var.pipeline_resolvers_path
}

//==================================================
//       Outputs generated by this module
//==================================================
output "functions" {
  value = local.functions
}
output "unit_resolvers" {
  value = local.unit_resolvers
}
output "pipeline_resolvers" {
  value = local.pipeline_resolvers
}
